FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web
ARG DATABASE_URL
RUN npm install
RUN command


RUN bun install
RUN bun run db:generate

RUN DATABASE_URL=${DATABASE_URL}  RUN bun run build
EXPOSE 3000
CMD [ "bun","run","start:web" ]